name: build-and-publish

on:
  push:
  schedule:
    - cron: '* * * * SUN'

jobs:
  nad-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Inbuilt NusantaraDevs Clang-12
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/nad-clang
        repository: najahi/oven
        tags: latest

  proton-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Inbuilt Proton Clang-12
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/proton-clang
        repository: najahi/oven
        tags: proton
